#!/bin/bash

# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

ln -sf ${OPENSHIFT_DATA_DIR}php ${OPENSHIFT_REPO_DIR}

if [ ! -d $OPENSHIFT_DATA_DIR/extensions ]; then
cp -r $OPENSHIFT_REPO_DIR/.openshift/extensions $OPENSHIFT_DATA_DIR/extensions
fi

if [ ! -d $OPENSHIFT_DATA_DIR/theme ]; then
cp -r $OPENSHIFT_REPO_DIR/.openshift/theme $OPENSHIFT_DATA_DIR/theme
fi

ln -sf ${OPENSHIFT_DATA_DIR}theme ${OPENSHIFT_REPO_DIR}php/
ln -sf ${OPENSHIFT_DATA_DIR}extensions ${OPENSHIFT_REPO_DIR}php/app/

if [ -z "$OPENSHIFT_MYSQL_DB_HOST" ]
then
echo 1>&2
    echo "Could not find mysql database. Please run:" 1>&2
    echo "rhc cartridge add -a $OPENSHIFT_APP_NAME -c mysql-5.5" 1>&2
    echo "then make a sample commit (add whitespace somewhere) and re-push" 1>&2
    echo 1>&2
fi

if [ -z "$OPENSHIFT_MYSQL_DB_HOST" ]
then
exit 5
fi

echo "Bolt CMS Installed/Updated"
